endpoint: wss://vira-stagenet-dancebox-rpc.a.moondev.network
mock-signature-host: true

import-storage:
  System:
    Account:
      - - - "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
        - data:
            free: "100000000000000000000000"
  Sudo:
    Key: "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"

  Registrar:
    registeredParaIds: []
