name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          executor/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        toolchain: nightly-2022-10-30
        components: rustfmt
        target: wasm32-unknown-unknown
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'yarn'
        registry-url: https://registry.npmjs.org/
    - run: yarn --immutable
    - run: yarn check
    - run: yarn build

    # version containing a hyphen, publish as beta, i.e: 1.0.0-1
    - run: |
        if npm pkg get version --workspace @tanssi/chopsticks | jq '."@tanssi/chopsticks"' | grep '-'; then TAG='--tag beta'; fi
        echo "NPM_TAG=$TAG" >> $GITHUB_ENV

    # Writes token to .yarnrc.yml. If written directly in .yarnrc.yml, it will cause an error
    - run: |
        echo npmAuthToken: "\${NPM_AUTH_TOKEN}" >> ./.yarnrc.yml

    - name: Publish @tanssi/chopsticks-executor
      run: yarn workspace @tanssi/chopsticks-executor npm publish --tolerate-republish --access public ${{ env.NPM_TAG }}
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish @tanssi/chopsticks-core
      run: yarn workspace @tanssi/chopsticks-core npm publish --tolerate-republish --access public ${{ env.NPM_TAG }}
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish @tanssi/chopsticks-db
      run: yarn workspace @tanssi/chopsticks-db npm publish --tolerate-republish --access public ${{ env.NPM_TAG }}
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish @tanssi/chopsticks
      run: yarn workspace @tanssi/chopsticks npm publish --tolerate-republish --access public ${{ env.NPM_TAG }}
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish @tanssi/chopsticks-testing
      run: yarn workspace @tanssi/chopsticks-testing npm publish --tolerate-republish --access public ${{ env.NPM_TAG }}
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Publish @tanssi/chopsticks-utils
      run: yarn workspace @tanssi/chopsticks-utils npm publish --tolerate-republish --access public ${{ env.NPM_TAG }}
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - run: |
        git checkout ./.yarnrc.yml
